apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ./../../base
  - namespace.yaml
patches:
  - path: patch_configmap.yaml
  - path: patch_deployment.yaml
labels:
  - includeSelectors: true
    pairs:
      environment: perf
