apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  template:
    spec:
      containers:
        - name: nginx
          image: nginx:stable
      tolerations:
        - key: "prod"
          operator: "Equal"
          effect: "NoSchedule"
          value: "true"
