apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    spec:
      tolerations:
        - key: "dev"
          operator: "Exists"
          effect: "NoSchedule"
          value: "true"
